name: CI/CD

on:
    push:
    pull_request:

jobs:
    images:
        runs-on: ubuntu-latest
        if: github.event_name == 'push' && github.repository == 'aulasoftwarelibre/idea' && github.ref == 'refs/heads/master'
        steps:
            -
                name: Checkout
                uses: actions/checkout@v2
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v1
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Cache Docker layers
                uses: actions/cache@v2
                with:
                    path: /tmp/.buildx-cache
                    key: ${{ runner.os }}-buildx-${{ github.sha }}
                    restore-keys: |
                        ${{ runner.os }}-buildx-
            -
                name: Login to GitHub Container Registry
                uses: docker/login-action@v1
                with:
                    registry: ghcr.io
                    username: ${{ secrets.CR_USER }}
                    password: ${{ secrets.CR_PAT }}
            -
                name: Build and push page
                uses: docker/build-push-action@v2
                with:
                    context: .
                    file: ./Dockerfile
                    push: true
                    tags: |
                        ghcr.io/aulasoftwarelibre/hacktoberfest-2020:latest
                    cache-from: type=local,src=/tmp/.buildx-cache
                    cache-to: type=local,dest=/tmp/.buildx-cache
           